import Navigator from '@/components/Navigator/Navigator'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Routes } from '@/models/routes.model'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hello Nextjs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
      
        {children}
        </body>
    </html>
  )
}
